services:

  backend:
    build: .
    # command: gunicorn MissleMoscowShopBackend.wsgi:application --bind 0.0.0.0:8000
    env_file: .env.dev
    entrypoint: ./entrypoint-web.sh
    ports:
      - 8000:8000
    depends_on:
      - postgre
    networks:
      - no-internet
      - has-internet

  postgre:
    image: postgres:16
    env_file: .env.dev
    ports:
      - "5432:5432"
    networks:
      - no-internet

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgre
    links:
      - postgre
    ports:
      - 8080:8080
    networks:
      - no-internet
      - has-internet

networks:
  no-internet:
    driver: bridge
    external: true
  has-internet:
    driver: host
    external: true