services:

  backend:
    build: .
    # command: gunicorn MissleMoscowShopBackend.wsgi:application --bind 0.0.0.0:8000
    env_file: .env.dev
    entrypoint: ./entrypoint-web.sh
    ports:
      - 8000:8000
    depends_on:
      - postgre
    networks:
      - no-internet
      - has-internet

  postgre:
    image: postgres:16
    env_file: .env.dev
    ports:
      - "5432:5432"
    networks:
      - no-internet

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgre
    links:
      - postgre
    ports:
      - 8080:8080
    networks:
      - no-internet
      - has-internet

  # minio:
  #   image: minio/minio:latest
  #   command: server --console-address ":9001" /data/
  #   env_file: .env.dev
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   # volumes:
  #     # - minio-storage:/data
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3

  # createbuckets:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     /usr/bin/mc alias set myminio http://minio:9000 root root1234;
  #     /usr/bin/mc mb myminio/mms;
  #     /usr/bin/mc anonymous set public myminio/mms;
  #     exit 0;
  #     "

networks:
  no-internet:
    driver: bridge
    external: true
  has-internet:
    driver: host
    external: true