version: "3"

services:
  backend:
    build: .
    # command: gunicorn MissleMoscowShopBackend.wsgi:application --bind 0.0.0.0:8000
    env_file: .env.dev
    entrypoint: ./entrypoint-web.sh
    ports:
      - 8000:8000
