# Generated by Django 4.2.4 on 2024-08-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
    ]
