# Generated by Django 4.2.4 on 2024-08-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0005_alter_attachment_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='primary',
            field=models.BooleanField(blank=True, null=True, verbose_name='Главная'),
        ),
    ]
