# Generated by Django 4.2.4 on 2024-09-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0006_attachment_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
    ]
