# Generated by Django 4.2.4 on 2024-08-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_order_created_at_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказов'},
        ),
    ]
